load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "urdfdom",
    linkopts = [
        "-lurdfdom_model",
        "-lurdfdom_world",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "pugixml",
    linkopts = ["-lpugixml"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "magic_enum",
    hdrs = glob(["third_party/magic_enum/include/magic_enum/*.hpp"]),
    includes = ["third_party/magic_enum/include"],
    visibility = ["//visibility:public"],
)


